const snesList = [
  { title: "Super Mario World", episode: 0 },
  // { title: "Legend of Zelda: A Link to the Past", episode: 13 },
  { title: "Super Castlevania IV", episode: 7 },
  { title: "Final Fantasy II", episode: 5 },
  { title: "Actraiser", episode: 5 },
  { title: "UN Squadron", episode: 4 },
  // { title: "Contra III", episode: 12 },
  // { title: "Lemmings", episode: 11 },
  { title: "Darius Twin", episode: 5 },
  { title: "Super Off Road", episode: 8 },
  { title: "F-Zero", episode: 1 },
  { title: "SimCity", episode: 1 },
  { title: "Legend of the Mystical Ninja", episode: 10 },
  { title: "Ys III: Wanderers from Ys", episode: 9 },
  // { title: "The Addams Family", episode: 12 },
  { title: "Gradius III", episode: 1 },
  { title: "Joe & Mac", episode: 9 },
  { title: "Super R-Type", episode: 3 },
  // { title: "Rival Turf!", episode: 13 },
  { title: "Drakkhen", episode: 2 },
  { title: "Populous", episode: 3 },
  { title: "Super Smash TV", episode: 10 },
  { title: "Final Fight", episode: 2 },
  { title: "Pilotwings", episode: 1 },
  { title: "John Madden Football", episode: 4 },
  { title: "Hal's Hole in One", episode: 2 },
  // { title: "PGA Tour Golf", episode: 11 },
  // { title: "True Golf Classics: Pebble Beach", episode: 13 },
  { title: "Lagoon", episode: 7 },
  { title: "True Golf Classics: Waialaie Country Club", episode: 6 },
  { title: "Hyperzone", episode: 2 },
  { title: "Paperboy 2", episode: 4 },
  { title: "Super Tennis", episode: 6 },
  { title: "Super Baseball Simulator 1.000", episode: 8 },
  // { title: "Raiden Trad", episode: 13 },
  // { title: "Extra Innings", episode: 11 },
  // { title: "Super Adventure Island", episode: 12 },
  { title: "D-Force", episode: 7 },
  { title: "Nolan Ryan's Baseball", episode: 9 },
  { title: "Super Bases Loaded", episode: 3 },
  // { title: "Smart Ball", episode: 11 },
  { title: "The Chessmaster", episode: 3 },
  { title: "Super Ghouls 'N Ghosts", episode: 6 },
  // { title: "WWF Super Wrestle Mania", episode: 12 },
  { title: "Bill Laimbeer's Combat Basketball", episode: 5 },
  { title: "Ultraman: Towards the Future", episode: 4 },
  { title: "Earth Defense Force", episode: 9 },
  { title: "Home Alone", episode: 7 },
  { title: "RPM Racing", episode: 6 },
  { title: "Pit Fighter", episode: 10 }
];

export default snesList;
